### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by jackhistoria** [raptor1001/Qt_RTSP_stream#2]
I tried to compile it in the qt creator on arch linux and it showed the following error:
Would like to help and fix it and push some to your project when I got it up and running. 
Please help me understand the structure you implemented on your windows machine? ill guess like openCV
if I red that right.

Like what have to be included/installed to make this compile. I will read through your code and it looks nice for what I see, your help just would save me some trouble. Am happy to contribute to your project.

01:48:03: Running steps for project IpFreely...
01:48:03: Configuration unchanged, skipping qmake step.
01:48:03: Starting: "/usr/bin/make" -j8
make: *** No rule to make target '/mnt/Data/projects/ThirdParty/singleapplication/singleapplication.cpp', needed by 'singleapplication.o'.  Stop.
01:48:03: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project IpFreely (kit: Desktop Qt 5.15.1 GCC 64bit)
When executing step "Make"
01:48:03: Elapsed time: 00:00.

**Comment by jackhistoria** [comment]
Ill guess i need the following libs in addition to qt5:

opencv_ffmpeg340_64.dll (opencv library)
opencv_world340.dll (opencv library)

boost_system-vc140-mt-x64-1_66.dll (boost library)
boost_filesystem-vc140-mt-x64-1_66.dll (boost library)

msvcp140.dll (ms visual studio 14)
vcruntime140.dll (ms visual studio 14)
vccorlib140.dll (ms visual studio 14)

windeployqt (qt 5.10.1)

Ill try to find sources to pull em from. Sure, help is appreciated or making them available would be nice :)

**Comment by jackhistoria** [comment]
Aah, you just stole it from here https://github.com/dac1976/IP-Freely to probably get yourself some references about being able to program. No worries, I won't say a word

**Comment by parkerlreed** [comment]
So what's the fix? 

FYI you could have just updated the issue I posted. Same thing. https://github.com/raptor1001/Qt_RTSP_stream/issues/1

**Comment by jackhistoria** [comment]
> So what's the fix?
> 
> FYI you could have just updated the issue I posted. Same thing. #1

Sry, no fix here. Check out the repository that created it. He mentioned on how to compile it in an issue. Gave up last night. The compilation is based on some library from dac1976 and what I already mentioned before. He has a longer info that describes the dependencies. If you are on arch linux you can install most of it with pacman or from the aur. 

Just check out  https://github.com/dac1976/IP-Freely  This guy here 
didn't forked it, he copied it without reference to the creator, thats what I ment with "stole"
